import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
	weight: "variable",
	style: ["italic", "normal"],
	display: "swap",
	subsets: ["latin"],
	variable: "--open-sans-font",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${inter.className} h-full antialiased`}>
			<body className="">{children}</body>
		</html>
	);
}
